export const SERVICE_NAME_MAP: Record<string, string> = {
  "Amazon S3": "Amazon Simple Storage Service (S3)",
  "Amazon SQS": "Amazon Simple Queue Service (SQS)",
  "Amazon SNS": "Amazon Simple Notification Service (SNS)",
  "Amazon ECR": "Amazon Elastic Container Registry",
  "Amazon ECS": "Amazon EKS",
  "AWS WAF": "AWS Web Application Firewall (WAF)",
  "Application Load Balancer": "Elastic Load Balancing",
  "ALB": "Elastic Load Balancing",
  "Elastic Load Balancer": "Elastic Load Balancing",
  "NAT Gateway": "Amazon Virtual Private Cloud (VPC)",
  "VPC": "Amazon Virtual Private Cloud (VPC)",
  "AWS Certificate Manager": "AWS Certificate Manager (ACM)",
  "Amazon RDS": "Amazon RDS for PostgreSQL",
  "Amazon Aurora": "Amazon Aurora PostgreSQL-Compatible DB",
  "Amazon Aurora PostgreSQL": "Amazon Aurora PostgreSQL-Compatible DB",
  "Amazon KMS": "AWS Key Management Service",
  "AWS KMS": "AWS Key Management Service",
  "AWS Secrets Manager": "AWS Secrets Manager",
  "Amazon DynamoDB": "Amazon DynamoDB",
  "Amazon Route 53": "Amazon Route 53",
  "Amazon CloudFront": "Amazon CloudFront",
  "Amazon CloudWatch": "Amazon CloudWatch",
  "Amazon GuardDuty": "Amazon GuardDuty",
  "Amazon ElastiCache": "Amazon ElastiCache",
  "Amazon ElastiCache for Redis": "Amazon ElastiCache",
  "Amazon OpenSearch Service": "Amazon OpenSearch Service",
  "Amazon Cognito": "Amazon Cognito",
  "Amazon EventBridge": "Amazon EventBridge",
  "Amazon API Gateway": "Amazon API Gateway",
  "Amazon Detective": "Amazon Detective",
  "Amazon Inspector": "Amazon Inspector",
  "Amazon Macie": "Amazon Macie",
  "Amazon DocumentDB": "Amazon DocumentDB (with MongoDB compatibility)",
  "AWS Shield": "AWS Shield",
  "AWS X-Ray": "AWS X-Ray",
  "AWS Lambda": "AWS Lambda",
  "AWS Config": "AWS Config",
  "AWS CloudTrail": "AWS CloudTrail",
  "AWS CloudFormation": "AWS CloudFormation",
  "AWS CodePipeline": "AWS CodePipeline",
  "AWS CodeBuild": "AWS CodeBuild",
  "AWS CodeDeploy": "AWS CodeDeploy",
  "AWS Backup": "AWS Backup",
  "AWS Systems Manager": "AWS Systems Manager",
  "AWS Database Migration Service": "AWS Database Migration Service",
  "AWS DMS": "AWS Database Migration Service",
  "AWS Security Hub": "AWS Security Hub",
  "AWS Fargate": "AWS Fargate",
  "Amazon EKS": "Amazon EKS",
  "Amazon EC2": "Amazon EC2",
  "Amazon EBS": "Amazon Elastic Block Store (EBS)",
  "Amazon Elastic Block Store": "Amazon Elastic Block Store (EBS)",
  "Amazon EFS": "Amazon Elastic File System (EFS)",
  "Amazon Elastic File System": "Amazon Elastic File System (EFS)",
  "Amazon VPC": "Amazon Virtual Private Cloud (VPC)",
  "Amazon Virtual Private Cloud (VPC)": "Amazon Virtual Private Cloud (VPC)",
  "Amazon Elastic Kubernetes Service (EKS)": "Amazon EKS",
  "Amazon Elastic Container Registry (ECR)": "Amazon Elastic Container Registry",
  "Application Load Balancer (ALB)": "Elastic Load Balancing",
  "AWS Key Management Service (KMS)": "AWS Key Management Service",
  "AWS Database Migration Service (DMS)": "AWS Database Migration Service",
  "AWS NAT Gateway": "Amazon Virtual Private Cloud (VPC)",
  "AWS Migration Hub": "AWS Migration Hub Refactor Spaces",
  "AWS Auto Scaling": "Amazon EC2 Auto Scaling",
  "AWS IAM": "AWS IAM Access Analyzer",
};
